### ISSUE TITLE
Login went wrong. Please try again.

### ISSUE THREAD

**Issue by jottunn** [saleor/saleor-platform#274]
After updating saleor-platform to the new images, I connect with default user/pass on localhost anymore.
![Screenshot from 2023-06-09 13-38-09](https://github.com/saleor/saleor-platform/assets/3864462/d13c49db-6062-4a17-855d-b0bea46c29d1)

The user exists because it used to work in previous versions.
The stdout from the containers don't show anything related to this.

Steps to reproduce:

`git clone https://github.com/saleor/saleor-platform.git`
`cd saleor-platform`
`docker compose build`
`docker compose run --rm api python3 manage.py migrate`
`docker compose run --rm api python3 manage.py populatedb --createsuperuser`
`docker compose up`
`navigate to localhost:9000`
`login with admin@example.com/admin`

**Comment by VibhakaraAcharya** [comment]
I am facing same issue. graphql url not getting mapped to host

![ss](https://github.com/saleor/saleor-platform/assets/35031785/c3580804-faab-4515-adfb-8ee08bb65012)

I have deployed on a VM. I have modified env ALLOWED_HOST={vm ip} Other urls works just fine. Dashboard is not working.  Request URL is still mapped to " localhost:8000/graphql " 

But if access  "http://{vm_ip}:8000/graphql" , am able to get response from graphql api !

**Comment by jottunn** [comment]
issue persists after latest update

**Comment by sinnfreiexposed** [comment]
Same here. I tried it with multiple super users and the default credentials on a VM and the host os (Ubuntu 20.04 & 22.04)

**Comment by TheKnottyCelt** [comment]
Same steps taken reproduces same result on fresh copy using Kali Linux on Raspberry Pi and also in a Kali Linux VM.  What I attempted:
```shell
$ docker-compose --rm api python3 manage.py createsuperuser
Starting saleor-platform_db_1     ... done
Starting saleor-platform_redis_1  ... done
Starting saleor-platform_jaeger_1 ... done
Creating saleor-platform_api_run  ... done
2023-07-13 15:12:25,780 WARNING saleor.core.jwt_manager RSA_PRIVATE_KEY is missing. Using temporary key for local development with DEBUG mode. [PID:1:MainThread]
Email: this@that.com
Password:
Password (again):
Superuser created successfully.

$ docker-compose up
``` 
When attempting to log in using the credentials I just created, I receive the same modal, `Login went wrong. Please try again.`

**Comment by sinnfreiexposed** [comment]
As I'm currently planning to use some kind of open source e-commerce solution with Next.js, I just recently found out about Saleor, so I still don't exactly know how we're supposed to set the platform or the standalone Docker containers up, but as we seem to be minority, it probably won't be an issue with the platform solution or Saleor itself. 🥲
I tried to setup the platform as described in the readme on WSL as I figured it could be some kind of Django issue with allowed hosts (still figuring that out, I have absolutely no idea how Django works and ofc too busy to read Saleor docs thoroughly), and yeah, it works on localhost. I guess we're just idiots

**Comment by TheKnottyCelt** [comment]
@sinnfreiexposed, thanks for that bit about `localhost`.  I can sign in now after ssh tunnelling, so that I can navigate to `localhost:9000`, rather than using the `IP` of the host machine.

**Comment by jottunn** [comment]
are you people saying you can sign in to the dashboard via localhost:9000, did you do anything else besides the steps I described above?

**Comment by sinnfreiexposed** [comment]
I set it up exactly like this (on Ubuntu Windows WSL).
Saleor recommends using
```
docker compose down --volumes db 
```
to remove the volumes if you have problems with migration. **Ofc this will remove all data stored in the databases**.

So I'm assuming you are just upgrading rather than freshly installing?

**Comment by TheKnottyCelt** [comment]
Ammending `docker-compose.yml` to include the VM machine's IP among the environment's `ALLOWED_HOSTS` rectified the issue for me.
```YML
services:
  api:
    environment:
      - JAEGER_AGENT_HOST=jaeger
      - DASHBOARD_URL=http://localhost:9000
      - ALLOWED_HOSTS=localhost,api,(vm_ip)
```

**Comment by sinnfreiexposed** [comment]
Did you change anything besides that in the compose file? I tested all the (possibly) relevant environment variables for many hours now and I always faced a CORS issue.

**Comment by TheKnottyCelt** [comment]
Adding the VM's IP allowed me to access the dashboard using the IP.  I also added the VM's `hostname` to the `ALLOWED_HOSTS` list and was then also able to access using the VM's `FQDN`.  I also repeated the process on a second machine (physical this time) with the same positive results.  But yes, that was the only line I changed in the `docker-compose.yml` file.

**Comment by sinnfreiexposed** [comment]
Hm, interesting. Yeah I also tried every possible configuration (at least regarding the envs), but still neither the ip nor the hostname works. I used docker compose all the time, and now I just figured to use docker-compose which kind of gives slightly different outputs. Didn't fix my problem (still get CORS errors), but I guess it's some problem with my network configuration then. 🥲

**Comment by jottunn** [comment]
> I set it up exactly like this (on Ubuntu Windows WSL). Saleor recommends using
> 
> ```
> docker compose down --volumes db 
> ```
> 
> to remove the volumes if you have problems with migration. **Ofc this will remove all data stored in the databases**.
> 
> So I'm assuming you are just upgrading rather than freshly installing?

This did it for me! If recreating the DB solves the issue, there must be some value in some table somewhere that doesn't get updated when you update to newer docker images.
